version: 1.4.0.{build}
image: Visual Studio 2017

configuration:
  - Release
environment:
  PROJECT: toofz.TestsShared
  COVERALLS_REPO_TOKEN:
    secure: K8eygAC5XfbsxJjLQwxQwrRX1zqxtfJPxpw1vUxYxEI8OduZRRhYfiLZ40tbD9s9
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_SERVICE_JOB_ID: '%APPVEYOR_JOB_ID%'
cache:
  - packages -> **\packages.config
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=

before_build:
  - appveyor-retry nuget restore -DisableParallelProcessing
build:
  project: $(PROJECT).sln
  verbosity: minimal

test_script:
  - ps: .\Scripts\Test-Project.ps1 -Assembly $env:PROJECT
after_test:
  - ps: .\Scripts\Submit-CodeCoverageResults.ps1

deploy_script:
  - ps: .\Scripts\Deploy-NuGetPackage.ps1